name: ci
on:
  schedule:
    - cron: '0 2 1 * *'
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - PubSub_pro8MHzatmega328
          - ConnectEthernetClient_pro8MHzatmega328
          - ConnectEsp8266WiFiClient_esp12e
          - LwtEsp8266WiFiClient_esp12e
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Build
        run: pio run -e $TARGET
        env:
          TARGET: ${{ matrix.target }}
