name: ci
on:
  push:
    branches:
      - '**'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install platformio
      - name: Build
        run: |
          pio run -e ConnectEsp8266WiFiClient_esp12e
          pio run -e ConnectEthernetClient_pro8MHzatmega328
          pio run -e ConSubNativeUnix
          pio run -e LwtEsp8266WiFiClient_esp12e
          pio run -e PubSub_pro8MHzatmega328
      - name: Start Mosquitto
        uses: Namoshek/mosquitto-github-action@v1.1.0
        with:
          version: '2.0.11'
          ports: '1883:1883'
          container-name: 'mqtt'
          config: ${{ github.workspace }}/test/native/mosquitto.conf
      - name: Test
        run: pio test -e NativeTest -v
